### ISSUE TITLE
Need to handle `model` as a `Scenario` key

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1022]
https://www.expectedparrot.com/content/21fe9f7d-16fd-422c-8784-5c72bea44dbb

I want to be able to do this in a notebook comparing/scoring model responses, where `model` is a metadata scenario key.

**Comment by rbyh** [comment]
We need to handle `model` as a key because it is automatically generated as one when a user does ```results.to_scenario_list()```

**Comment by johnjosephhorton** [comment]
It's in the 'Result' object - so it's the 'select' code that has the bug.

<img width="594" alt="Screenshot 2024-11-11 at 6 04 49 AM" src="https://github.com/user-attachments/assets/62b862a4-9eaa-4b7b-ae2c-54bd316a23e5">

```python
from edsl import Results 
r = Results.pull('64c8ae87-9bb8-45f6-8100-3c9a76eba4c2')
r[0]['scenario']
```

**Comment by johnjosephhorton** [comment]
It would be a lot of work to fix this fully - but as a reasonable fix, I'm changing the name when we have a duplicate name e.g., 'model' and 'model' and warning the use: 

<img width="1377" alt="Screenshot 2024-11-11 at 6 54 04 AM" src="https://github.com/user-attachments/assets/cc3404df-4f7d-44c7-8dba-0c3677ea05f4">
