### ISSUE TITLE
Gemini pro is printing question prompt to the screen when new question is run

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1028]
https://www.expectedparrot.com/content/d6241e83-1efb-44bf-8ea8-2c2a0a533c05

Not seeing this for other platforms' models.

**Comment by johnjosephhorton** [comment]
Maybe check if the GoogleInferenceService.py has a stray print statement in the created model?

**Comment by rbyh** [comment]
yep

<img width="715" alt="image" src="https://github.com/user-attachments/assets/01ed17ca-eb9f-4d06-b420-64efbdf6ddcc">
