### ISSUE TITLE
"Human-readable question" is printing twice

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1054]
<img width="1276" alt="image" src="https://github.com/user-attachments/assets/19bfc295-b7df-4686-9b94-ab12ea896cc7">

**Comment by johnjosephhorton** [comment]
Can you share this actual question? I can't re-produce with the default QuestionRank example

**Comment by johnjosephhorton** [comment]
@rbyh can you help with this?

**Comment by rbyh** [comment]
Closing for now. Will reopen if it reappears.
