### ISSUE TITLE
Question parameter `include_comment=False` not working for all types

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1063]
Error thrown for linear scale, yes/no, budget, topk

https://www.expectedparrot.com/content/4cc9e610-899c-410c-bb88-fd58d6cb9f64

**Comment by rbyh** [comment]
Eg with question numerical the field name is present in "columns" but there is an error if you try to select it:
https://www.expectedparrot.com/content/5a39b972-8379-41fc-b88e-e5f1ee27c50b

**Comment by johnjosephhorton** [comment]
^ isn't that because it's "comm**m**ent.*" i.e., typo? But we should throw a more informative error message i.e., "Did you mean?..."

**Comment by rbyh** [comment]
Lol whoops yes. Ok now:
<img width="423" alt="image" src="https://github.com/user-attachments/assets/943584cd-d167-49c1-9ae1-2762ae2f339a">


BUT: if I have not added an agent the agent instruction should not be present, correct?

<img width="816" alt="image" src="https://github.com/user-attachments/assets/897aa496-fad8-4840-90f0-c18510d85a39">

**Comment by rbyh** [comment]
I think they should all show "None" for consistency.
