### ISSUE TITLE
Scenario example with image not working

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1071]
Responses appear to be static? New questions using the example scenario with `has_image=True` are not generating new responses:

https://www.expectedparrot.com/content/d91645c9-c74b-4b1f-98ab-733aff23605d

**Comment by rbyh** [comment]
Also not working with scenario generated from local image using `from_image()` method:

https://www.expectedparrot.com/content/fb6e647b-87e8-4aa4-bae7-f0dfe75d26cc

**Comment by johnjosephhorton** [comment]
Great - catch - it's a caching bug - I'm on it. 

<img width="523" alt="Screenshot 2024-09-21 at 6 52 44 AM" src="https://github.com/user-attachments/assets/6a727a00-d07c-4789-89bd-ffb27b9c17a6">
