### ISSUE TITLE
Unrecognized exception message calling Model.available(service="google")

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1117]
<img width="1122" alt="image" src="https://github.com/user-attachments/assets/216d98e4-0fc8-4aca-9f16-10d861d39c16">

**Comment by johnjosephhorton** [comment]
Yeah, this is some Google SDK thing. I don't think it's anything where doing wrong. It appears to be a warning. I could try to catch it but my inclination is to leave it for now.

**Comment by rbyh** [comment]
ok closing for now
