### ISSUE TITLE
Validation problem "should have split the new line" - John

### ISSUE THREAD

**Issue by benjamin-manning** [expectedparrot/edsl#1119]
<img width="1722" alt="Screenshot 2024-10-04 at 09 25 58" src="https://github.com/user-attachments/assets/8fc6c810-0975-4fa8-b5ad-25efc68beb22">

**Comment by johnjosephhorton** [comment]
@benjamin-manning you don't by any chance still have the HTML file w/ this example do you?

**Comment by benjamin-manning** [comment]
@johnjosephhorton I just sent on slack
