### ISSUE TITLE
Feature Request: Scrollable progress bar

### ISSUE THREAD

**Issue by benjamin-manning** [expectedparrot/edsl#1120]
<img width="925" alt="image" src="https://github.com/user-attachments/assets/4d891610-ea66-4626-a94a-d4f57730d30b">

See above: the progress bar only lets you see a small subset of the current jobs. It would be nice if I could scroll through and see them all.

**Comment by johnjosephhorton** [comment]
Much better solution coming soon, @benjamin-manning cc: @apostolosfilippas

**Comment by benjamin-manning** [comment]
:)
