### ISSUE TITLE
Typo `reponse` in yes-no answering instructions

### ISSUE THREAD

**Issue by MaxGhenis** [expectedparrot/edsl#1121]
https://github.com/expectedparrot/edsl/blob/f7b23f66636af211f1b16080f8af7c2930b5e822/edsl/questions/templates/yes_no/answering_instructions.jinja#L2-L5

Should be `respond` then `response`.

I think this explains the other instances of `reponse` in the repo: https://github.com/search?q=repo%3Aexpectedparrot%2Fedsl%20reponse&type=code

**Comment by rbyh** [comment]
Thank you!
