### ISSUE TITLE
Create `prompts()` method for jobs to show prompts and estimated costs 

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1129]
Functions similarly to `run()`.
It generates a scenario list with estimates of what the prompts and costs will be, that can be displayed as a table.

It should have:
- user prompt
- system prompt
- model
- estimated tokens
- estimated price
- run unconditionally OR specified dependency/condition
- question instructions
- indication of whether question will be populated with other info not available yet - eg piped answer

**Comment by johnjosephhorton** [comment]
The new method is now:
```
jobs.show_prompts()
```
The `prompts` method returns a dataset.

**Comment by johnjosephhorton** [comment]
cc: @zer0dss just FYI - the estimated cost thing - the list of interviews is already the length of the questions x the agents x the scenarios x models so we didn't need that multiple factor

**Comment by zer0dss** [comment]
@johnjosephhorton I've added the custom multiplier because the models have different prices

**Comment by johnjosephhorton** [comment]
Hey @zer0dss - but in Jobs, this "prompts()" method will already duplicate each prompt for every model, so iterating through the models will over-count. 

<img width="355" alt="Screenshot 2024-10-15 at 5 37 51 AM" src="https://github.com/user-attachments/assets/5b6f1f50-0124-4d9c-b882-b9b9d2ebb007">

I added a cost method to the "prompts()" command that I think shows how we should do this. Can you take a look?
