### ISSUE TITLE
Creating a method for de-duping a scenario list

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1147]
This is useful if you are creating scenarios from results where there may be duplicate key/values (eg agents voted on things, and you want to create scenarios for top voted things).

**Comment by johnjosephhorton** [comment]
Can you say a bit more? Is it literally taking a ScenarioList and removing duplicate items i.e., two Scenarios that are identical?

**Comment by rbyh** [comment]
Yes, just that.

**Comment by rbyh** [comment]
Appreciate that they would be cached, but eliminating python steps for doing this outside of EDSL would be nice.

**Comment by rbyh** [comment]
Excellent, forgot about it!

**Comment by rbyh** [comment]
Actually, getting error that it doesn't exist:

<img width="741" alt="image" src="https://github.com/user-attachments/assets/319eedb4-6368-4822-99cd-9895a8a1a6d0">
