### ISSUE TITLE
Create prompts that can use QuestionFreeText (or other question types) to return a dictionary

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#115]
It can be useful to have the agent return a dictionary (eg agent traits) but this is not addressed with existing question type prompts. Eg trying to manipulate QuestionFreeText to do this throws an error because the response is not a string:

```
q_ranges = QuestionFreeText(
    question_name = "ranges",
    question_text = """You are being asked to design a survey about job posts at Upwork.
    Provide a dictionary where the keys are dimensions of freelancers
    and the values are lists of possible options for those dimensions."""
)
q_ranges.by(model).run().select("ranges").print()
```

<img width="1010" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/8667515b-6738-4851-b463-8951ff7ef45d">

**Comment by johnjosephhorton** [comment]
Another approach is to do something like this where you break in into steps:

https://embed.deepnote.com/dceaad48-76c8-4ecb-a682-3eea29a1bfb2/3ca7ff714cdb4e978b93345638d23d2c/7d72edc51bff40edab51344cf0c6ad24?height=1797.0999755859375
