### ISSUE TITLE
Question `loop()` method should automatically make question names pythonic

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1171]
Example: https://www.expectedparrot.com/content/e19f1ab9-66d3-46c2-8f15-937acd87345c

Eg, this generates error `QuestionCreationValidationError: `question_name` is not a valid variable name`:

```
from edsl import QuestionFreeText, ScenarioList

q = QuestionFreeText(
    question_name = "enjoy_{{ sport }}",
    question_text = "Do you enjoy {{ sport }}?"
)

s = ScenarioList.from_list("sport", ["ice fishing", "ski jumping"])

questions = q.loop(s)
```

**Comment by johnjosephhorton** [comment]
I'm reluctant to do this automatically on behalf of the user - I think it's better to just return an appropriately detailed error message that they can then fix.

**Comment by rbyh** [comment]
I think we should at least just change spaces to underlines and change to lowercase. Otherwise we're really limiting the ability to use the scenario key in the question name.

**Comment by johnjosephhorton** [comment]
why not just add another scenario entry with a proper name? I hear what you're saying but it's a real anti-pattern in software to assume what people mean when they explicitly wrote what they wanted to happen.

**Comment by rbyh** [comment]
Closing this as duplicative of other discussion. We should add optional loop parameters for renaming and making unique question names.
