### ISSUE TITLE
Object save method is inserting extra "." in filename

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1197]
<img width="412" alt="image" src="https://github.com/user-attachments/assets/5cbd664b-029a-4311-91fd-8bb8f8eb1c8f">

https://www.expectedparrot.com/content/5a22112b-80ef-4a47-873a-e27ccee55d7b

**Comment by johnjosephhorton** [comment]
Ah - so I think what I had intended was that the user would save without the extension: 
<img width="458" alt="Screenshot 2024-10-28 at 6 56 55 AM" src="https://github.com/user-attachments/assets/f8774eff-2fc7-4f90-87ab-473dfa46dfff">
But it would work if they added the extension manually. But I don't think that's great (and obviously I'm screwing up the string). 
A few thoughts: 
1. It is good that "json.gz" tells you what it is (compressed json), but that makes it more complex and makes it hard for the user to remember. I wrote it and I couldn't remember.
2. We could save everything as "your_object.edsl" or "your_object.ep" which would me less clear what it is but more clear that it was something EP created 
3. It would be good to have a "universal load" - maybe `obj = edsl.load('my_thing.ep')` and will get it right
4. It would nice if this all worked seamlessly with coop as a backup / alt location 
5. It should probably work well w/o a name e.g., `my_object.save()` does something sensible like look through the directory is increments the object count as needed to store it as "my_object_2.ep`

**Comment by rbyh** [comment]
My preference would be to allow the user to drop or include the extension. I would not use something unexpected eg ".edsl".

**Comment by rbyh** [comment]
Method is also missing for `Model` (but not `ModelList`):
<img width="688" alt="image" src="https://github.com/user-attachments/assets/e3a65b25-dac9-4402-b189-0502b758643e">

**Comment by johnjosephhorton** [comment]
Consider that if you save a word document, you aren't asked to remember it's "docx"

**Comment by johnjosephhorton** [comment]
re: Model - good catch. This is because Model is not actually a Base object - it's a like a cut-out for LanguageModel. I'll add this method!

**Comment by rbyh** [comment]
Exactly
