### ISSUE TITLE
Missing comment field in results

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1202]
https://www.expectedparrot.com/content/f3ba4452-882f-4632-bff9-608356e57226

**Comment by johnjosephhorton** [comment]
It's definitely there in the generated token string (see 'content'), which means it's not getting parsed correctly: 

<img width="1010" alt="Screenshot 2024-10-28 at 11 55 23 AM" src="https://github.com/user-attachments/assets/563b3ce7-29df-4e7c-bcd4-c241e70f0f99">

**Comment by johnjosephhorton** [comment]
This seems to only be an issue on remote inference. Working on it.

**Comment by johnjosephhorton** [comment]
Here's a succinct example
```python
from edsl import QuestionMultipleChoice

q = QuestionMultipleChoice(
    question_name = "smallest_prime",
    question_text = "Which is the smallest prime number?",
    question_options = [0, 1, 2, 3]
)

results_remote = q.run()
results_local = q.run(disable_remote_inference = True)
```

**Comment by johnjosephhorton** [comment]
It's a serialization issue:
<img width="797" alt="Screenshot 2024-10-30 at 10 11 48 AM" src="https://github.com/user-attachments/assets/86ada2a8-f8b0-4ec0-8ed8-88c12bfb1f43">

**Comment by johnjosephhorton** [comment]
@zer0dss did you have some bandwidth to investigate?

**Comment by zer0dss** [comment]
@johnjosephhorton Yes, I will check it.

**Comment by johnjosephhorton** [comment]
@zer0dss Can you let me know when the edsl on coopr has this fix?

**Comment by zer0dss** [comment]
@johnjosephhorton The testing endpoint is update with the new version and the issue is fixed.
