### ISSUE TITLE
Modify `AgentList.from_csv()` to allow a specified "name" field in addition to traits

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1203]
Currently, the method uses all columns as traits and does not allow "name" as a key because it is a separate parameter of an agent. It would be convenient to allow a user to specify the agent names simultaneously to avoid doing it programmatically after import.

**Comment by johnjosephhorton** [comment]
Added this.

**Comment by rbyh** [comment]
@johnjosephhorton It is not working for me? https://www.expectedparrot.com/content/0291c975-6f72-4547-80af-c0752fdea2ec
