### ISSUE TITLE
Render error for prompts when adding optional question parameters

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1220]
When I add optional parameters to questions I am unable to call the `show_prompts()` method on the survey.
The parameters are also not appearing in the prompts when the question is run:

https://www.expectedparrot.com/content/abfd2745-4cc0-4717-bd12-65e84f87bd97

**Comment by johnjosephhorton** [comment]
Oof - **great** catch. The problem is that question instructions are getting passed as string not a jinja2 template, so it doesn't have that render method that prompts do. On it.

**Comment by johnjosephhorton** [comment]
I think this is fixed.
