### ISSUE TITLE
Create service to look up token prices

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#125]
URL is here:
https://docs.google.com/spreadsheets/d/1SAO3Bhntefl0XQHJv27rMxpvu6uzKDWNXFHRa7jrUDs/edit#gid=0

**Comment by apostolosfilippas** [comment]
this should be a coop API call! Prices should be in cents - no floating numbers when dealing with $ @johnjosephhorton

**Comment by johnjosephhorton** [comment]
In terms of denominating prices, I think to @apostolosfilippas point, it might be better to track all prices as two integers: 
(number of cents, number of tokens that  buys you) 
so that we always store precisely. So, if, price is 1 cent for a million tokens, we could store as 
(1, 1_000_000) 

We need to distinguish token types. I think we'll also want the coop price service to serve up prices we set and then we have a service that flags price drops where we can then update prices.
