### ISSUE TITLE
Token authentication doesn't work when running code from .py script. (Running from notebook works).

### ISSUE THREAD

**Issue by zer0dss** [expectedparrot/edsl#1253]
@onmyraedar can you replicate this?

https://github.com/user-attachments/assets/aeb0ad10-4de8-4031-bccd-0037948a3822

**Comment by zer0dss** [comment]
Thanks @onmyraedar, I've removed the commented API keys and it worked.

**Comment by onmyraedar** [comment]
Fixed in https://github.com/expectedparrot/edsl/pull/1274 - if you have all of your keys, you no longer have to log in twice for EDSL settings
