### ISSUE TITLE
Agent `traits_presentation_template` does not work with remote inference

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1260]
It works locally but not remotely:
https://www.expectedparrot.com/content/b95727a0-01d1-4505-8db3-edc26cd321cc

**Comment by johnjosephhorton** [comment]
@zer0dss I *think* this is an issue that will require an update to the edsl version of Coop. Could you help confirm?

**Comment by rbyh** [comment]
Closing this as it's working fine for me now
Ty @zer0dss  @onmyraedar !

**Comment by onmyraedar** [comment]
Yep, sorry about this one - it was actually not an EDSL issue, but something we had to fix on the Coop end of things.
