### ISSUE TITLE
F-string is causing scenario double braces to be rendered as single braces

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1265]
https://www.expectedparrot.com/content/c72bac27-c500-4815-8628-ebe15dc73526

**Comment by rbyh** [comment]
Disregard -- it is not being passed correctly.

**Comment by rbyh** [comment]
See updated notebook ^^ comparing with/out f-string and scenarios.

**Comment by johnjosephhorton** [comment]
It works for me on this branch: 
https://github.com/expectedparrot/edsl/tree/light_lm_refactor
Here's the nb: https://www.expectedparrot.com/content/7eb26d68-efdf-4bc1-853e-32fd40add38e
Note we're still intentional showing a warning.
