### ISSUE TITLE
Auth URL not clickable in VS Code IPython NB

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#1267]
The URL in the Jupyter output is not clickable in VS code, at least on Linux: 

![Screenshot from 2024-11-12 13-47-03](https://github.com/user-attachments/assets/085f7f5b-0648-4b5f-9d10-dc4222a1ac40)

I think we want to detect that we're in a notebook environment and show with a IPython display: 

```
from IPython.display import Markdown

url = "https://example.com"
display(Markdown(f"[Click here to open the URL]({url})"))
```

**Comment by rbyh** [comment]
I am not getting the message at all in jupyter nb:

https://www.expectedparrot.com/content/6c962069-3b15-4d36-a6cb-49ea278e7e2a

**Comment by onmyraedar** [comment]
This should have been fixed with https://github.com/expectedparrot/edsl/pull/1274 - please let me know if you're still experiencing issues! If not, we can close.
