### ISSUE TITLE
Question.get_instructions() still showing comment instruction when include_comment=False

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1275]
Comment instruction is (correctly) removed from show_prompts() but still appearing in get_instructions:
https://www.expectedparrot.com/content/d0bf4eb4-3d30-4c88-bfd7-c239f8563593

**Comment by johnjosephhorton** [comment]
Ah - no, this is right.  get_instructions returns the jinja2 template that has the *logic* for comment / code.
