### ISSUE TITLE
Serialization issue with `include_comment=False` 

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1277]
If you add  `include_comment=False` to a question it should *not* retrieve a cached response where the comment field was included:

https://www.expectedparrot.com/content/36331333-48f7-497a-af6c-527f80d52fe5

**Comment by rbyh** [comment]
Showing it is likely a serialization issue: https://www.expectedparrot.com/content/2e017b7b-0c22-4478-9695-6f1481cd379d

**Comment by rbyh** [comment]
Local is also adding // to comment field: https://www.expectedparrot.com/content/c0265bd6-d5bc-4424-adc6-589f90f12eca

**Comment by johnjosephhorton** [comment]
Thanks - good catch. It's not getting serialized & if it's not getting serialized, it will not work for remote inference

<img width="529" alt="Screenshot 2024-11-14 at 12 03 48 PM" src="https://github.com/user-attachments/assets/66e1c13e-b5a2-405e-84ec-1db8e3998561">
<img width="725" alt="Screenshot 2024-11-14 at 12 04 02 PM" src="https://github.com/user-attachments/assets/47e6d16e-bc1f-4d3c-8616-ffed610dad84">
