### ISSUE TITLE
Add table expand feature to show individual scenarios in a scenariolist

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1326]
It would be nice to automatically see individual scenarios:
<img width="614" alt="image" src="https://github.com/user-attachments/assets/41112135-b17e-4195-b826-a43e5c31ec83">

**Comment by johnjosephhorton** [comment]
So you can do this with ".table()" - if you have a better verb name LMK. I could also a message "to see entries, .table()" - that's just HTML at the bottom.
