### ISSUE TITLE
Consider option to not attach the user's cache to their Results object

### ISSUE THREAD

**Issue by onmyraedar** [expectedparrot/edsl#1328]
Attaching the cache to the Results object is taking up a huge amount of space for remote inference users. Consider the following example from prod:
```python
from edsl import Results

results = Results.pull("bb2cc658-ac99-4daf-9107-af67391cffc6")

results_dct = results.to_dict()

for key, value in results_dct.items():
    value_as_string = str(value)
    print(key, f"{len(value_as_string):,}")
```
gives me this:
```
data 2,621,870
survey 1,338
created_columns 2
cache 183,212,709
task_history 1,470,219
```
Asking because a user's remote inference job failed due to their Results being so long that it exceeded the database driver's limit, and I think a lot of this character count is probably the attached cache. 
![image](https://github.com/user-attachments/assets/6ba640a3-02c3-4006-bfe2-e7191dc21e40)

**Comment by johnjosephhorton** [comment]
Ah - thank you! So I'm running our unit tests right now w/ that removed. TBH, I don't recall why I did that - maybe the test will tell! More generally, we should start looking for places where we can do some optimizations. I developed edsl w/o any attention paid to memory or computation but now we need to tighten up as the usage increases.

**Comment by onmyraedar** [comment]
Resolved in https://github.com/expectedparrot/edsl/pull/1329
