### ISSUE TITLE
Revise remote inference user message 

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1333]
A new user may be confused by the Job URL that is displayed in remote inference messages (what is a "Job"?). To avoid potential confusion, we could revise the following message that is currently displayed:
<img width="1017" alt="image" src="https://github.com/user-attachments/assets/8ee97575-785c-4508-9369-f0616da2bfa1">

Suggested revised message:

```
Remote inference has been activated. 
Your survey is being sent to the Expected Parrot server...
Your survey is running at the Expected Parrot server...
You can view a progress report here: <link to progress bar>
Job details are available at your Coop account: <link to job page -- not just the UUID>
Your survey has been run. Results are available at Coop: <link>
```

**Comment by onmyraedar** [comment]
Hi! We don't have pages for individual jobs yet - is this something you think we should create?

**Comment by rbyh** [comment]
No, I think I meant the remote inference page where you see the job. I think the main issues are (i) someone could easily no know what exactly we mean by "job" and (ii) a UUID is not memorable. So giving a link to where they can see the details would be helpful.

**Comment by rbyh** [comment]
I think it can be shown right away? Because you'll probably want to see details especially if it fails, not just if successful?
