### ISSUE TITLE
Stop logic throwing a TypeError when questions are skipped

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#134]
When stop logic is applied, the questions are not/answered as expected based on the given logic, but there are 2 errors thrown for each non-answered question:
1. `IntervierErrorPriorTaskCanceled` --> we should suppress this as expected behavior
2. `TypeError` --> need to resolve this

Code to reproduce errors:
```
from edsl.questions import QuestionYesNo, QuestionFreeText
from edsl import Survey, Agent

q_exercise = QuestionYesNo(
    question_name = "exercise",
    question_text = "Do you enjoy exercising?"
)

q_favorites = QuestionFreeText(
    question_name = "favorites",
    question_text = "What are your favorite ways to exercise?"
)

survey = Survey(questions = [q_exercise, q_favorites])

survey.add_stop_rule("exercise","exercise == 'No'")

personas = [
 'Fitness enthusiast',
 'Athlete',
 'Yoga practitioner',
 'Bodybuilder',
 'Marathon runner',
 'Sedentary individual',
 'Couch potato',
 'Gym hater',
 'Exercise avoider',
 'Lazy person'
]

agents = [Agent(traits={"persona":p}) for p in personas]

results = survey.by(agents).run()
```
<img width="826" alt="stoplogicerrors" src="https://github.com/goemeritus/edsl/assets/50664588/043ae26f-8b8f-4bfc-8076-72da2e404812">

**Comment by johnjosephhorton** [comment]
I couldn't reproduce this error - it runs fine. I suspect some of the changes I made in latest version fixed this.
