### ISSUE TITLE
`Survey.show_flow()` not working in Colab

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#1383]
<img width="628" alt="image" src="https://github.com/user-attachments/assets/4377a69d-1eb3-4d29-8c51-f8146c1e8f55" />

**Comment by johnjosephhorton** [comment]
It looks like we just need to use IPython to display: 
![image](https://github.com/user-attachments/assets/2e6ec72a-59fc-4a18-a767-8bc9279851b3)

**Comment by rbyh** [comment]
This is something to mention in docs instructions about Colab for now?

**Comment by johnjosephhorton** [comment]
I think it's fixed now - I was just displaying something wrong

Just did this on Colab
<img width="305" alt="Screenshot 2024-12-18 at 2 09 08 PM" src="https://github.com/user-attachments/assets/c6f34961-cc3a-4576-8de1-a72e121b0eba" />
