### ISSUE TITLE
QuestionLinearScale response is sometimes invalid "0" when question_options start at "1"

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#18]
LLM will sometimes return "0" when the question_options are [1,2,3, ... ], even when the question_text notes the scale (eg, "...on a scale from 1 to 7": 

<img width="768" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/26f4d765-cbd3-4363-88db-7b8c2ffdf10d">

<img width="1064" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/e6a6eb48-cf86-496c-93d7-516bc9c5e5ac">

Perhaps the prompt is too confusing:
<img width="155" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/6f161484-840a-4c64-96a7-89e4ad1bc49c">

**Comment by apostolosfilippas** [comment]
@rbyh check the commit [b718410](https://github.com/goemeritus/edsl/commit/b718410984d0ea3b40592b924097c87eb3c4d20c) I think it should fix this
