### ISSUE TITLE
Feature Request: Create a method for adding a set of parameterized questions to the same survey

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#19]
We should create a method for adding a set of parameterized questions all to the same survey. Scenarios does not currently allow this -- when you add a parameterized Question to a Survey and then do `survey.by(scenarios)` to insert parameter values you create a new Job for each parameter value, i.e., the single-question survey is administered separately for each parameter value.

For example, this method creates a set of parameterized questions that we can then add to a survey using the `add_question()` method (or `Survey(questions=[...])` construction) in order to have them all within a survey:
```
def add_product_rating_questions(survey):
    for product in PRODUCTS:
        question_name = f"rating_{product.replace(' ', '_').replace('-', '').lower()}"
        question_text = f"Rate your desirability for {product} right now (1-7). Use 1 to 7 scale, please:"
        survey.add_question(QuestionLinearScale(question_name=question_name, question_text=question_text, question_options=list(range(0, 8))))
```

Conceptually, what we want is a "vertical" application of question scenarios within a survey.

**Comment by johnjosephhorton** [comment]
I think this can almost always be accomplished by just an appropriately defined set of single-question parameters and we don't want to encourage this style anyway.
