### ISSUE TITLE
Need ability to add keys later with improved error message

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#201]
If I skip adding a key (purposely or inadvertently) I don't have an option to add it later on when generating results. I get a non-specific error message that the survey is not being answered.

<img width="755" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/089f885e-df46-43a3-953f-f1900ae2e72b">

**Comment by johnjosephhorton** [comment]
I think we have a partial fix here with running the "has_api_key_check" at running
