### ISSUE TITLE
Issues/exceptions need to be ready to copy-and-paste

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#235]
General error/exceptions message needs better instructions for how to see individual error messages:
<img width="745" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/b134ab8b-df7c-4b7d-9fdd-da3e456061c9">

This is readable but lots of wasted space and you can't copy a single column of text, making it hard to debug:
<img width="1131" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/e4a5ea27-aadb-48c1-9717-c9c8f4c9fc73">

**Comment by johnjosephhorton** [comment]
Need to extract just the main names from the exceptions. Think about how to display...

<img width="1470" alt="Screen Shot 2024-04-10 at 8 49 50 PM" src="https://github.com/expectedparrot/edsl/assets/407218/9e2529f0-1622-429e-b6ea-13d17f0cc254">
