### ISSUE TITLE
Survey.run() throwing CancelledErrors

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#256]
Code to reproduce error:

```
from edsl import Survey
Survey.example().run()
```

<img width="983" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/0fd184ce-1639-44f6-9001-78df2d9d5c3d">

<img width="988" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/7bc10544-42ad-4cbe-bb23-b51fabd86bf0">

**Comment by johnjosephhorton** [comment]
Got it - I've got a fix for it.

**Comment by johnjosephhorton** [comment]
Can you see if our current tests are passing?

**Comment by johnjosephhorton** [comment]
We should first write a test that fails for this bug
