### ISSUE TITLE
Modify Results and Coop so that they can be imported the same way as Agent, Scenario, Survey

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#267]
This code will generate an error
```
from edsl import Results
```
<img width="744" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/b20b81a2-0ede-4a21-958e-67c8c43e24df">

This will generate the same error:
```
from edsl import Coop
```

The required code is:
```
from edsl.results import Results
from edsl.coop import Coop
```
It would be convenient to be able to import all of those classes in the same way.

**Comment by johnjosephhorton** [comment]
This is mostly just a function of our __init__ files. I think with `Results` though - we dont' really expect the user to importing do we? I guess maybe yes because they might be doing 
```
results = Results.pull("<coopid>")
```
right? Ok, I think we do want this. @rbyh is that right?

**Comment by johnjosephhorton** [comment]
Done
