### ISSUE TITLE
Select + Print do not print columns in the order listed

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#273]
<img width="1024" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/0a9281ef-99d2-465a-b30c-72d0cbbe5c69">

**Comment by johnjosephhorton** [comment]
That's a pretty_labels dict right?

**Comment by johnjosephhorton** [comment]
Can't re-reproduce - @rbyh can you create a minimal example w/o pretty_dict that fails? 

<img width="631" alt="Screen Shot 2024-04-14 at 10 36 02 PM" src="https://github.com/expectedparrot/edsl/assets/407218/cbe98408-2730-4f66-95b5-61f4f381bba6">
