### ISSUE TITLE
Updated `print` method: let's change it to top+left justification

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#277]
Right justification does not display as nicely:

<img width="1131" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/b40df2cd-1b1e-47a2-a35e-531f4e7e3a9e">

**Comment by johnjosephhorton** [comment]
While I agree this doesn't look great in all cases, making this change will require over-riding some internal Jupyter Notebook CSS that seems complex and brittle. I suggest we live with this for now. cc: @rbyh

**Comment by johnjosephhorton** [comment]
(I spend a 1/2 hour an investing & trying to get it to work - not just a guess by me :)
