### ISSUE TITLE
Add method for batching scenario values

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#371]
This can be useful where you have a long list of items that you want to search over or condense and need to batch them into Scenario objects for review (you'd prefer to do all at once but it's too long).

```
q_errors = QuestionList(
    question_name = "errors",
    question_text = """Consider the following list of search terms for an online marketplace: {{ search_terms_list }} 
    Now return a non-duplicative list containing only those search terms that are non-categorizable errors or nulls, 
    such as 'nan', 'NaN', 'n/a' or 'null'.""",
)
```

**Comment by johnjosephhorton** [comment]
This sounds like the "flatten" method of a scenario list, but if it's not, feel free to re-open.
