### ISSUE TITLE
Add a method for combining and flattening list of results

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#378]
For example, say I have a data labeling task where I want to perform the labeling in batches - eg, I may use a scenario that is a subset of the the data. When I generate results, I want to combine them into a single labeled dataset (eg, combine and flatten lists or dicts). It would be useful to have methods to do that, mirroring new methods for batching the data at the outset.

**Comment by johnjosephhorton** [comment]
Can you say a bit more about how this would work? I don't quite follow but this sounds interesting.

**Comment by johnjosephhorton** [comment]
I think we can do this now.
