### ISSUE TITLE
Consider adding an indicator when a question was not administered / survey ended because of conditional logic

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#382]
eg indicate that follow-on questions were not administered, the responses were *not* "None"

<img width="592" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/54d29802-3ff6-4878-9cc6-1515299ffc6f">

**Comment by johnjosephhorton** [comment]
I'm going to close this one as 'wontfix' because I think None is the better (or least bad) solution here, but @rbyh I think you should note this very clearly in the docs.
