### ISSUE TITLE
Survey.add_rule() method is not correctly administering skip logic

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#383]
Example:
```python
from edsl.questions import QuestionMultipleChoice, QuestionNumerical, QuestionFreeText
from edsl import Survey

q1 = QuestionMultipleChoice(
   question_name = "best_pet",
   question_text = "What is the best kind of pet?",
   question_options = ["Dog", "Fish", "Lizard", "Parrot"]
)
q2 = QuestionNumerical(
   question_name = "ideal_fish",
   question_text = "What is the ideal number of fish to own?"
)
q3 = QuestionFreeText(
   question_name = "parrots",
   question_text = "What are parrots known for?"
)
survey = Survey([q1, q2, q3]).add_rule(q1, "best_pet == 'Dog'", q3)
results = survey.run()
results.select("best_pet", "ideal_fish", "parrots").print(format="rich")
```
Stop rule is correctly displayed in Survey object:
<img width="378" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/0624372d-9d61-4802-a4f3-69859abf3c05">
<img width="336" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/8ce706a2-b355-4696-8bf1-949275125f17">

But the response to q3 is still "None" when it should have been administered based on the rule:
<img width="581" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/0c0ff5b7-764d-4de8-9c14-9a8e2c0de2da">

**Comment by johnjosephhorton** [comment]
This is part of the code where the bug likely lives: 

https://github.com/expectedparrot/edsl/blob/49a41cf08075fe0bf1bfd34082750553f89c66a2/edsl/jobs/interviews/InterviewTaskBuildingMixin.py#L187
