### ISSUE TITLE
QuestionMultipleChoice does not allow long list of question_options that may be desirable for data labeling tasks

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#386]
Consider allowing a long list of question_options (for data labeling) to avoid this error:

<img width="988" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/2932e33f-8ac3-479c-b485-a782d9ffd251">

**Comment by johnjosephhorton** [comment]
yeah - we should remove restrictions like this that we put in just for...reasons. If someone wants to try a giant question, why stop them? These 1M token context window models could easily handle
