### ISSUE TITLE
Object .example() method may be confusing

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#402]
We are telling people to run the example() method to see examples of objects but this does NOT show the user:
- Which parameters are not/required 
- A template for actually creating an object

We should consider ways of expressing this information at the same time
eg the user does not need to enter the question_type to create a question object:
<img width="418" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/71bfb907-7cf4-4032-806a-de7f36b62b33">

**Comment by johnjosephhorton** [comment]
Agreed - two thoughts. 

1. We should encourage people to use help(X) to get our docs in context (and include URL to docs)
2. If we get the 'code' method working for all objects, we can also easily show how that object is constructed
