### ISSUE TITLE
Results `sort_by()` method does not behave as expected

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#459]
I expect it to sort fields in the order that I have applied it, but it does it in reverse:
<img width="566" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/346d601e-3af4-4111-948a-cbca6ded002f">

**Comment by johnjosephhorton** [comment]
Can you say a bit more here - what's the expected behavior?

**Comment by johnjosephhorton** [comment]
I see. This might be challenging because it would require the dataset to have a "memory" of what is sorted by and I'd prefer to keep it stateless. What about is sorted could take multiple keys, like this: 
```
results.sort_by('a', 'b')
``` 
which would sort by a, then b.

**Comment by johnjosephhorton** [comment]
New version does sort this way - can you update docs, @rbyh ?
