### ISSUE TITLE
Add 'piping' option where previous answers can be slotted into to question text / options in future questions

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#471]
<img width="561" alt="Screenshot 2024-05-11 at 6 22 34 AM" src="https://github.com/expectedparrot/edsl/assets/407218/74d27fff-1b6b-4bb3-b864-de96f72595d8">

**Comment by benjamin-manning** [comment]
3b. or have many other models answer

4. I don't want the model to have a memory of entire previous questions, but I want to pipe in items that are answers from a subset of previous questions in a given survey into a new question as portions of that new questions---either in the question itself, or as answer options.

5. Memory, but just a list of previous choices, no need for question repeats. Like in John's repeated prisoner's dilemma making it say "you responded to the following questions 6 times ```Question```. Here are those responses: list of answers without repeating question

**Comment by rbyh** [comment]
I think this is the important distinction from targeted memory methods --- you want to access only the response, not the context of the question or fact that it was asked.

**Comment by benjamin-manning** [comment]
yup! exactly. I haven't used targeted memory much, but from my understanding, my request is different, and I hope, useful for people so worth implementing :)

**Comment by rbyh** [comment]
Current `compose_questions()` looks for the q1 question name to be present as a parameter of the q2 question text, but we should also allow the q1 answer to become the q2 answer options (multiple choice, checkbox, etc), ie modify this:
<img width="907" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/5f319c8a-c2a0-4078-9a3f-b0b004cf68f8">

**Comment by rbyh** [comment]
eg using free text or list question to elicit a selection is not ideal because the agent is likely to differently format unless we add detailed formatting instructions:
<img width="931" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/7ced633a-4cf2-42b8-aab3-9de5a59d98e2">

**Comment by rbyh** [comment]
Note that we also do not want/need the field name duplicatively nested within the response to the composed/piped question:
<img width="502" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/4ebd11ce-2fd8-424d-823c-b9c74d5a3a8c">
