### ISSUE TITLE
Create memory options for a repeated question

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#476]
For example, if I want to prompt an agent to pick a random number 5 times in a row I can do this with `QuestionList`, but if I want to vary the number of prior responses in memory I do not have a way to add this rule to the individual question, I have to repeat the same question multiple times in a survey and then add the rule, which is inefficient, easy to mess up.

**Comment by rbyh** [comment]
Eg I want to do something like this:

<img width="867" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/7c4abbdc-3a10-419c-ae85-c67a6ae08521">

**Comment by johnjosephhorton** [comment]
@rbyh Could you say a bit more about the use case?

**Comment by rbyh** [comment]
I'm going to close this for now and see if it bothers me again. I think it's actually ok to have to repeat a q in a survey if you're applying different rules for each administration of it, to keep you aware of what was included.
