### ISSUE TITLE
Was `results.to_list(flatten=True)` inadvertently reverted?

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#482]
Seems to have stopped flattening (this was fine yesterday):

<img width="587" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/631c212f-e4f0-4019-8b9c-84638a662e48">

**Comment by johnjosephhorton** [comment]
@rbyh I don't think so - but it doesn't seem to be working right. Can you create a code example that fails this test w/o making an API call? I.e., use a direct-question-answering method like we do for the other tests in `edsl\test`

**Comment by rbyh** [comment]
I forgot we already have results method `flatten()` but it also does not seem to be working:

Expected (test):
<img width="657" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/f30c769e-c285-4e1b-bf9e-52ed09722de1">

Actual:
<img width="567" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/7d6c4abd-9199-4e01-925d-8f397ace035d">

**Comment by rbyh** [comment]
Current behavior:
<img width="451" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/71b20a01-2106-4c4e-a50e-2f2c3a52fccb">

**Comment by johnjosephhorton** [comment]
@rbyh Could you paste a failing example in code? Above is an image

**Comment by rbyh** [comment]
Code to reproduce issue:
```
from edsl.questions import QuestionList

results = QuestionList.example().run(n=5)

results.select("list_of_foods").to_list()

# This still shows a list of lists:
results.select("list_of_foods").to_list(flatten=True)
```

**Comment by johnjosephhorton** [comment]
I think this is good new - @rbyh can you check & if OK, close?

**Comment by rbyh** [comment]
Fixed
