### ISSUE TITLE
Add sphinx autodoc for LanguageModel

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#507]
We want the autodoc so the references thorough the documentation link back to this class: 

file:///Users/john/tools/edsl/.temp/docs/language_models.html

**Comment by rbyh** [comment]
They already do? 

Top of an .rst page should look like this:
```.. _language_models:```

And then references back to that page should look like this:
```:ref:`language_models````

<img width="495" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/5cff32a2-6262-4498-9a8f-145aac8803be">

**Comment by rbyh** [comment]
done
