### ISSUE TITLE
Make Survey code sample executable

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#521]
I think we should have a hard rule against non-executable code samples: 

<img width="743" alt="Screenshot 2024-05-19 at 11 36 00 AM" src="https://github.com/expectedparrot/edsl/assets/407218/4fc4a2ca-3434-43f0-8d75-09af1a98d956">

Proposal: Just replace it w/ three simple QuestionFreeText w/ the appropriate edsl imports

**Comment by rbyh** [comment]
done
