### ISSUE TITLE
No non-working code in docs

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#551]
People will try to run it, esp. python beginners and be confused. It also prevents us from eventually adding automated tests of all examples in the code. 

<img width="472" alt="Screenshot 2024-05-24 at 6 16 56 AM" src="https://github.com/expectedparrot/edsl/assets/407218/d3b55b16-9898-430e-bebb-dcdca74b9fc7">

**Comment by rbyh** [comment]
Done
