### ISSUE TITLE
The `first()` method is throwing an exception message that should be ignored

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#559]
When I rerun it the message disappears:

<img width="956" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/9f785d31-6a7b-46e7-b483-ae7d77ecb2b3">

[ WIll add code to reproduce ]

**Comment by rbyh** [comment]
This is to avoid hackier version `to_list()[0]` which still works fine

**Comment by johnjosephhorton** [comment]
that should be "topic == 'caller requests' - we should throw a more helpful exception here I think

**Comment by rbyh** [comment]
Ah of course whoops!

**Comment by johnjosephhorton** [comment]
It's such an easy mistake to make though that we should throw a custom exception w/ more detail - probably use `re` to find a naked assignment in the expression

**Comment by johnjosephhorton** [comment]
Got a fix for this - in next PR
