### ISSUE TITLE
Results method `to_scenario_list()` not working

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#562]
I believe the problem may be that `to_scenario_list()` preserves the prefixes from the results but there is an error if you try to use them. This should be fixed, and I think the default should be `remove_prefixes=True` so that this works fine:

Code to reproduce: 
```
from edsl.questions import QuestionMultipleChoice, QuestionList
from edsl import Scenario

q1 = QuestionMultipleChoice(
    question_name = "color",
    question_text = "What color is the sky?",
    question_options = ["Black", "Red", "Blue"]
)

results = q1.run()

q2 = QuestionList(
    question_name = "examples",
    question_text = "What are some things that are {{ color }}?"
)

scenarios = results.select("color").to_scenario_list()

results = q2.by(scenarios).run()
results.select("examples").print()
```

<img width="157" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/fc73d27b-0bac-4936-8c8a-db4c7bdbe023">

**Comment by johnjosephhorton** [comment]
I've got this fixed, but I found a new issue - running a job is modifying the underline scenario object by adding the edsl serialization info

**Comment by rbyh** [comment]
The default should be `remove_prefix=True` and I also think we should throw an error immediately when you try to run a survey and the question placeholders do not match the scenarios (right now, if you do not specify remove prefix it tries and you discover only from comments).
