### ISSUE TITLE
Add ability to use scenarios for question_options

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#576]
Eg, I am running a question where I prompt the agent to take a list and condense it into a set of answer options that I use in the follow-on question. But I am not able to input them in the new question as scenarios, as that only works for the question text.

Consider this together with piping.

**Comment by johnjosephhorton** [comment]
Can you give an example of the syntax you’d like to use here?

**Comment by rbyh** [comment]
Eg the response to QuestionList is a list. I want to pipe that into the follow on question as a scenario of the question_options, not just a list that I input.
