### ISSUE TITLE
Error Installing edsl Package

### ISSUE THREAD

**Issue by zhangxinghub** [expectedparrot/edsl#593]
I encountered an error while installing the edsl package using pip install edsl. The error seems to be related to the statsmodels package, which is required for pyproject.toml-based projects.

**Details:**

When attempting to install the edsl package, I received the following error message:

`Failed to build statsmodels
ERROR: Could not build wheels for statsmodels, which is required to install pyproject.toml-based projects`

To troubleshoot, I tried installing the statsmodels package separately using pip install statsmodels. The statsmodels package installed successfully without any errors.

**System Information:**

Operating System: I tried Windows 10 and Windows 11
Python Version: Python 3.12.3
Pip Version: pip 24.0

Any guidance on resolving this error would be greatly appreciated.

**Comment by johnjosephhorton** [comment]
@zer0dss @apostolosfilippas I think where only using this in some quite optional features - in addition to helping  @zhangxinghub if we can, maybe we should make this optional? I'm not very well-versed in best practices for making packages optional

**Comment by zhangxinghub** [comment]
I discovered that the edsl package is compatible with Python 3.9 - 3.11. I was initially using Python 3.12.3. After switching to Python 3.11, the issue was resolved, and the edsl package installed successfully without any errors.

Thank you for your attention and assistance.

**Comment by apostolosfilippas** [comment]
Thanks @zhangxinghub! I will look into 
(i) removing the statsmodel dependency -- or make an optional if it is not necessary 
(ii) making EDSL compatible with Python 3.12.x 
Leaving the issue open until we come up with a good fix for this.
