### ISSUE TITLE
Extra slash in coop URL

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#644]
```
'visibility': 'unlisted',
 'url': 'https://chick.expectedparrot.com//explore/cac
```

**Comment by johnjosephhorton** [comment]
See the extra slack after the `.com` - assuming that's not intention?  
'https://chick.expectedparrot.com//explore/cac

**Comment by apostolosfilippas** [comment]
@johnjosephhorton 

you probably have a trailing / in your .env var. Edited coop client to remove if there in commit [8ba3745](https://github.com/expectedparrot/edsl/pull/648/commits/8ba3745cb1a8ece1994b3c53955469e10a4e01a4)
