### ISSUE TITLE
Use triple quotes in the EDSL object representation (__repr__ method)

### ISSUE THREAD

**Issue by zer0dss** [expectedparrot/edsl#647]
We have an issue when formatting Python code for an object returned by __repr__ method. When there are text values on multiple lines the current solution doesn't work because it uses simple quotes '' ([example for question class)](https://github.com/expectedparrot/edsl/blob/ed8be697413b5d1af939c9456a495b3a143617ba/edsl/questions/QuestionBase.py#L227)

**Comment by johnjosephhorton** [comment]
Thanks - would it be as simple as changing this line to use triple quotes? 

https://github.com/expectedparrot/edsl/blob/ed8be697413b5d1af939c9456a495b3a143617ba/edsl/questions/QuestionBase.py#L232

**Comment by zer0dss** [comment]
There are two more places where a similar change have to be made
