### ISSUE TITLE
Conjure: `get_themes()` method silently failing

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#679]

**Comment by rbyh** [comment]
No exception is generated, but it looks like the `ScenarioList` is not actually used -- the question does not include parameters for it:

<img width="793" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/1922e173-69cc-4ff9-9047-daa25758bac0">
<img width="793" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/1922e173-69cc-4ff9-9047-daa25758bac0">

**Comment by johnjosephhorton** [comment]
Good catch - so it looks like I'm actually just passing the values using an f-string and not using the Scenario?

**Comment by rbyh** [comment]
Exactly.

We should also consider improving to remove nulls. In our example, they are stored as "missing", so it should be a broad net.

I'm still getting empty results, haven't figured out why yet because the question looks ok.

**Comment by rbyh** [comment]
Closing this as I've got it working now. Not sure if it was a version update issue or what but will reopen if it reappears. We can delete the unnecessary line in the method though.
