### ISSUE TITLE
Model / Infra coverage

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#68]
- [x] Google AI Studio
- [ ] Google Model Garden
- [x] OpenAI
- [ ] Mistral 
- [x] Deep Infra
  - [x] Llama models
  - [ ] Mixtral
- [ ] Hugging Face
- [ ] Open Router
- [ ] Azure
  - [ ] Llama models
  - [ ] OpenAI models
- [ ] AWS Bedrock
  - [ ] Llama Models
  - [ ] Claude V2

**Comment by zoharbabin** [comment]
perhaps instead of implementing each model separately, use https://github.com/BerriAI/litellm ?
