### ISSUE TITLE
Conjure: Add method for ignoring Qualtrics columns not needed for analysis

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#684]
<img width="981" alt="image" src="https://github.com/expectedparrot/edsl/assets/50664588/651252e6-79d7-4bd5-b89f-3c82b09655c0">

**Comment by johnjosephhorton** [comment]
I think the keep/drop is a better approach than ex-ante screening out, but if you disagree @rbyh please re-open.
