### ISSUE TITLE
Consider deprecating Cache.remote

### ISSUE THREAD

**Issue by onmyraedar** [expectedparrot/edsl#686]
We added remote caching logic in `Jobs.run()`, but the Cache object itself has an existing remote attribute that I believe was used to handle the earlier iteration of remote caching.

What should we do about `Cache.remote`? Should we delete that attribute and its logic, or keep it and explicitly override the value of `Cache.remote` with the value from the Coop settings?

Ex.: if the user passes `q.run(cache=Cache(remote=False))`, but remote caching is set to true on Coop, we would need to override.

**Comment by johnjosephhorton** [comment]
We should - I'll re-factor it out.
