### ISSUE TITLE
Multiple calls to get_rate_limits in OpenAIService slows down the exectime of surveys when using cache.

### ISSUE THREAD

**Issue by zer0dss** [expectedparrot/edsl#699]
This code uses a cache to run the survey. The first call to survey run takes ~2s; for the remaining 99 calls in normal cases, the results should be obtained instantly from the cache, but it takes ~1s.

```python
from edsl import QuestionFreeText,QuestionMultipleChoice
from edsl import Cache,Survey
import time

s = Survey(questions=[QuestionFreeText.example(),QuestionMultipleChoice.example()])
c = Cache()

for i in range(0,100):
    start = time.time()
    res = s.run(cache=c)
    print("exec time ",time.time()-start)
```

**Comment by johnjosephhorton** [comment]
Good catch - Maybe we just put an LRU cache decorator on the limit lookup
function for now?

**Comment by johnjosephhorton** [comment]
@zer0dss I think a good solution here would be: 

1. we keep alternative/back up lists of services in models hard-coded in `edsl/enums.py` that we can use
2. we create a warning of some kind to (us) as developers when a API model lookup reveals a discrepancy between our backup list (as a sign we need to update)
3. we don't throw an exception when we can't access the API list but we do print a warning for the user that we're using a stored list

Thoughts on this approach?

**Comment by zer0dss** [comment]
@johnjosephhorton This is the solution that I was thinking too. Until now I think this is the only place where we have this type of requests that slows down the execution ( checking for available models)

**Comment by johnjosephhorton** [comment]
Ok - excellent that we're aligned. Do you want to build it?

**Comment by zer0dss** [comment]
Yes, I will add it.

**Comment by johnjosephhorton** [comment]
Hey @zer0dss not to pressure you, but do you have an ETA on this one? It's holding up some stuff I want to do on this new 'Study' module.

**Comment by zer0dss** [comment]
@johnjosephhorton Currently I am working on a coop task. I can do a fast patch today that will cache the values (a similar patch to the one applied to the method that checks for available models). How is this blocking the work on the Study module, do you want to push a new edsl version and have this running optimization in place?

**Comment by johnjosephhorton** [comment]
No worries - I'll do a quick fix myself. 

re: blocking - so I'm trying to debug some evidence that a study is making an rogue API call on a replication when calls should purely be from the cache. And the most error-free way to check is to turn off wifi :)

**Comment by zer0dss** [comment]
Ok, it makes sense to me now why this blocks your work on the study module.
