### ISSUE TITLE
Need help with nltk dependency

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#726]
@zer0dss @apostolosfilippas I could use some help with this - so in a nutshell, I want to add the `nltk` as a dependency but it requires this `nltk.download('stopwords')` command to be run post-install. ChatGPT suggested I could add a post-install script to `pyproject.toml` 

```
(edsl-py3.10) john@Johns-MacBook-Air edsl % cat scripts/postinstall.py 
import nltk

def main():
    nltk.download('stopwords')

if __name__ == "__main__":
    main()%                                                                                                                                                                           (edsl-py3.10) john@Johns-MacBook-Air edsl % 
```
But this doesn't seem to be working. I suppose I could add a link to the .github actions yaml giving specific instructions how to install, but that doesn't likely work for users. Suggestions?

_Originally posted by @johnjosephhorton in https://github.com/expectedparrot/edsl/issues/725#issuecomment-2212485504_

**Comment by zer0dss** [comment]
@johnjosephhorton Using the poetry post-install command didn't work for me either. A solution is to add nltk.download in the function where it is needed (or inside an __init__.py script), so it will be downloaded when required.

**Comment by johnjosephhorton** [comment]
Thanks - I ended up just hard-coding in the stop words I needed from nltk.
