### ISSUE TITLE
`Results.select().print()` not always printing in selected order

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#760]
<img width="1021" alt="image" src="https://github.com/user-attachments/assets/919e3e68-ad20-4e03-b2fe-e5f6d8c4965e">

**Comment by rbyh** [comment]
Possibly a prompts issue - not repeating issue with other components.

**Comment by johnjosephhorton** [comment]
Please create a chick object I can use

**Comment by rbyh** [comment]
@johnjosephhorton 
https://chick.expectedparrot.com/content/c3835649-8d85-41b0-a218-41270a19d1ed

**Comment by johnjosephhorton** [comment]
hey sorry - this one got zero-d out - can re-produce another example for me?

**Comment by rbyh** [comment]
survey: 'fe726239-2cb3-4360-b7bf-9c88dcdc1027'

results (showing user prompts are not printed in the specified order): '26177c2f-a357-481a-9859-1a9d881ef823'

**Comment by rbyh** [comment]
<img width="1035" alt="image" src="https://github.com/user-attachments/assets/7da46e95-0a30-4c46-9c24-9d4c4a9bdeab">
