### ISSUE TITLE
Exception raised for `Survey.example()`

### ISSUE THREAD

**Issue by onmyraedar** [expectedparrot/edsl#770]
This code:

```python
from edsl import Survey

result = Survey.example().run()
```

gives me the following exception:

![image](https://github.com/user-attachments/assets/b0b79328-736c-45d0-8f68-a28cdee509ec)

![image](https://github.com/user-attachments/assets/28ed8980-2af0-436a-a06c-66f3938735b2)

It works when I comment out this line in the `example` method:

```python
s = s.add_rule(q0, "q0 == 'yes'", q2)
```

**Comment by johnjosephhorton** [comment]
I think I fixed this with most recent PR?

**Comment by onmyraedar** [comment]
My bad, got it!
