### ISSUE TITLE
QuestionFreeText generating JSON errors

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#78]
QuestionFreeText generating JSON errors in providing list responses (even without "list" specified in question_text)
This is happening with GPT 3.5 and 4

<img width="1247" alt="image" src="https://github.com/goemeritus/edsl/assets/50664588/86f3d852-e00a-46bb-90db-4f4dc1d1171f">

**Comment by johnjosephhorton** [comment]
For the failing question, can you put a minimally reproducible example in a code block? E.g., 
```python
from edsl import QuestionFreeText 
q = ...
```
I have a new procedure I'd like us to follow

**Comment by johnjosephhorton** [comment]
that's fine - I'll probably write it in a loop w/o caching to try to force an exception

**Comment by johnjosephhorton** [comment]
your code references an m5?

**Comment by johnjosephhorton** [comment]
Great - so @apostolosfilippas @benjamin-manning - whenever we have a question where the JSON will not parse, please 
1. Create an Issue and label as a bug
2. Put a minimally reproducible example in the issue, in a codeblock
3. If you're feeling up for it, add to `edsl/integration/test_tricky_questions.py` 
4. Confirm failure 

This will force us to solve problems here. Here's a first example: 
https://github.com/goemeritus/edsl/commit/037683d2de42531727570ec571d1f9355deb83cc

**Comment by johnjosephhorton** [comment]
Since big re-factor of question-answering, this doesn't come up much so I'm going to close.
