### ISSUE TITLE
High temperature failure with uninformative errors

### ISSUE THREAD

**Issue by benjamin-manning** [expectedparrot/edsl#791]
If one runs this: https://github.com/apostolosfilippas/homo_silicus/blob/main/analysis/horton.py at a high temperature (1+) it fails on some of the API calls, but it is not clear what the problem is from the error messages.

**Comment by johnjosephhorton** [comment]
@benjamin-manning Can you post some error messages + screenshots to help debug?

**Comment by benjamin-manning** [comment]
@johnjosephhorton 
<img width="1089" alt="Screenshot 2024-07-22 at 09 16 50" src="https://github.com/user-attachments/assets/fe90257e-fd65-494d-890e-e6f2389c9c50">
<img width="1089" alt="Screenshot 2024-07-22 at 09 17 06" src="https://github.com/user-attachments/assets/288f86ad-a2bf-44c3-acf0-ed8a13b65d7f">

**Comment by johnjosephhorton** [comment]
@apostolosfilippas The 'undefined Results' makes me think it's an older version of edsl? It might make sense of him to install from github main branch instead
