### ISSUE TITLE
Results `to_pandas()` header issues

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#804]
![image](https://github.com/user-attachments/assets/4c06dcdb-7e30-4a1e-88d1-77ca629eb1f7)

**Comment by johnjosephhorton** [comment]
Can you do some research on this @rbyh ? I suspect this is more of a Jupter notbook issue than an "us" issue - maybe try saving dataframe to a file and then opening in a new Jupyter session w/o any reference to edsl

**Comment by rbyh** [comment]
Yeah I think it's a jupyter thing
