### ISSUE TITLE
Results `sql` header issues

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#805]
![image](https://github.com/user-attachments/assets/4d70928f-0b4c-4056-a387-8bc4538214b5)

**Comment by johnjosephhorton** [comment]
This is likely a pandas issue. See this for ideas: 
https://chatgpt.com/c/ca3c7da4-c11e-46ba-a5a1-06fe0570967a
If you want to play around here and give suggestions/advice, I ca implement.

**Comment by johnjosephhorton** [comment]
bump, @rbyh

**Comment by rbyh** [comment]
Closing this because it is a pandas issue.
