### ISSUE TITLE
Results `to_pandas()` orders alphabetically instead of specified order

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#806]
![image](https://github.com/user-attachments/assets/184b1fb3-468d-4b8c-93b5-da53aeead3e6)

**Comment by johnjosephhorton** [comment]
@rbyh Can you create a coop results object for this example?

**Comment by rbyh** [comment]
{'description': None,
 'object_type': 'survey',
 'url': 'https://chick.expectedparrot.com/content/51bd47c9-07cf-47fd-ab70-4218f7f0d9e3',
 'uuid': '51bd47c9-07cf-47fd-ab70-4218f7f0d9e3',
 'version': '0.1.30.dev5',
 'visibility': 'unlisted'}

{'description': None,
 'object_type': 'results',
 'url': 'https://chick.expectedparrot.com/content/0288d8ef-4130-49e9-b9eb-4168d9ea6fa2',
 'uuid': '0288d8ef-4130-49e9-b9eb-4168d9ea6fa2',
 'version': '0.1.30.dev5',
 'visibility': 'unlisted'}

{'description': None,
 'object_type': 'notebook',
 'url': 'https://chick.expectedparrot.com/content/03af3c52-43df-4241-af14-01fc838327c0',
 'uuid': '03af3c52-43df-4241-af14-01fc838327c0',
 'version': '0.1.30.dev5',
 'visibility': 'unlisted'}
