### ISSUE TITLE
Docstring for QuestionNumerical suggests it accepts `instructions` but this is not the case

### ISSUE THREAD

**Issue by benwhalley** [expectedparrot/edsl#866]
https://github.com/expectedparrot/edsl/blob/main/edsl/questions/QuestionNumerical.py

When trying to set different instructions, I get:

```
TypeError: QuestionNumerical.__init__() got an unexpected keyword argument 'instructions'
```

**Comment by johnjosephhorton** [comment]
Thanks @benwhalley - we're on it!

**Comment by rbyh** [comment]
Thank you @benwhalley! Making this edit right now. Please let us know of any issues using question types or anything else - we appreciate the feedback!

**Comment by benwhalley** [comment]
Hi - I think there is also a problem for free text questions. It's impossible to override `instructions` for these and it always returns the default instructions.
The code in QuestionBase is a little indirect but it seems like the issue is there?
