### ISSUE TITLE
Document how to set OPENAI_BASE_URL to localhost for use with Ollama?

### ISSUE THREAD

**Issue by benwhalley** [expectedparrot/edsl#900]
Is this possible? It seems like the base_url needs to be settable (e.g. use be able to use Azure) but I can't work out how.

Alternatively, is it just possible to create an openai client object manually and set edsl to use that?

**Comment by zer0dss** [comment]
@johnjosephhorton I will handle this and also I think I will extend it to be compatible with [VLLM](https://github.com/vllm-project/vllm) too.

**Comment by johnjosephhorton** [comment]
awesome - thanks @zer0dss - great idea. LMK if you need, say, Google Collab or Lambda labs credits to get a GPU capable of running these 'locally' - I tried running Ollama on my laptop and it borked my GPU :(

**Comment by zer0dss** [comment]
@johnjosephhorton @benwhalley I've added Ollama integration. Until we merge it in the main version @benwhalley  you can use it by installing edsl from this branch https://github.com/expectedparrot/edsl/tree/add_aws_bedrock. Also an example is available in this notebook [edsl_with_offline_inference_services.ipynb](https://github.com/expectedparrot/edsl/blob/add_aws_bedrock/docs/notebooks/edsl_with_offline_inference_services.ipynb)
