### ISSUE TITLE
Exceptions report is missing info for `agent` causing it to not render

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#910]
Exceptions report is not rendering because it is missing agent info.
In this example, the question text pipes an agent trait.
Notebook showing the issue:
https://www.expectedparrot.com/content/3be8d9ef-fb61-4d87-b5e0-9e820770ac42

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/85ba8ccb-f89e-486a-bf95-7452b704c6d7">
<img width="999" alt="image" src="https://github.com/user-attachments/assets/dc07b347-6ad7-4fd3-95ba-0731f667a8d8">
<img width="994" alt="image" src="https://github.com/user-attachments/assets/7f102d62-424b-428a-9a41-5c443fbd9be6">

**Comment by zer0dss** [comment]
This is fixed in merged PR https://github.com/expectedparrot/edsl/pull/912
