### ISSUE TITLE
Getting `QuestionCreationValidationError` when rerunning question `loop()` method example code

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#914]
Example of `loop()` method I am rerunning:
https://www.expectedparrot.com/content/9fee0c5c-6f4f-4a4d-be43-8207e9c0bcec

<img width="736" alt="image" src="https://github.com/user-attachments/assets/74092e34-d35b-4c81-b968-647e02d951af">

**Comment by rbyh** [comment]
When I take the `{{ placeholder }}` out of the `question_name` (which should not work because then it is no longer unique for each scenario), I get a different error that the question object has no attribute `loop`: 

<img width="836" alt="image" src="https://github.com/user-attachments/assets/3235c858-098a-4e2f-a873-e4a4042e40c4">

**Comment by johnjosephhorton** [comment]
I can't re-produce this - it runs fine for me. Hmm. Let's try laptops side by side again.
