### ISSUE TITLE
Allow `Survey` rules methods to use inequality expressed with `<>` 

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#920]
Currently, an inequality must be expressed using `!=`.

Example code to reproduce syntax error exception that is thrown for `<>`:
https://www.expectedparrot.com/content/820a1231-01aa-47b6-b220-33eb6fe97ec5

**Comment by johnjosephhorton** [comment]
So expression language exactly mirrors what you can do in Python. I'd rather not change that contract. What we could do is is, if the user uses a "<>" we could throw a meaningful exception

**Comment by johnjosephhorton** [comment]
I added an exception here
