### ISSUE TITLE
Inference models inheriting from OpenAIService don't call the correct base URL to retrieve the available models.

### ISSUE THREAD

**Issue by zer0dss** [expectedparrot/edsl#932]
```python
from edsl import Model

print(Model.available("openai"))
print("#############")
print(Model.available("deep_infra"))



```
The code returns the same models just changing the service name.
<img width="1109" alt="Screenshot 2024-08-28 at 19 35 12" src="https://github.com/user-attachments/assets/63c67b08-a5e3-4b73-9d1a-768a27020407">

**Comment by johnjosephhorton** [comment]
ah  - whoops. For why I was doing this - I was getting an OS / too many files open error from creating too many connections - the openai client opens up some file to check something. It happened with a  jobs w/ 500+ interviews, so I wast trying to economize. We'll need to do something else here then...(and probably should re-create the OS error in a test)

**Comment by zer0dss** [comment]
Ok, I understand the problem. I will think about it and add an extra patch
