### ISSUE TITLE
`QuestionFreeText` may need more checks for escaping characters

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#959]
<img width="1120" alt="image" src="https://github.com/user-attachments/assets/4bb8db61-4a87-4135-a05f-eb1fbec37f15">

**Comment by johnjosephhorton** [comment]
Got it - can you create a notebook for me?

**Comment by rbyh** [comment]
<img width="1084" alt="image" src="https://github.com/user-attachments/assets/4287bca3-8564-40dc-b242-2a2bb0d73167">

**Comment by johnjosephhorton** [comment]
I think probably improved now? Can you grab the string that starts "The key interpersonal relationship..."

**Comment by johnjosephhorton** [comment]
I added a block to the exception report that should give the code necessary to re-produce an example, so long as the question doesn't have piping / memory: 

<img width="1044" alt="Screenshot 2024-09-02 at 7 19 17 AM" src="https://github.com/user-attachments/assets/870678e9-3255-4bac-9a4a-2ffa9d40df8b">

For reporting bugs, please always include this code or flag if it doesn't generate.
