### ISSUE TITLE
For the interview exception report, for each question, include the final answer; debug None getting passed to validation

### ISSUE THREAD

**Issue by johnjosephhorton** [expectedparrot/edsl#967]
There seem to be cases where the model eventually does answer:
<img width="1428" alt="Screenshot 2024-09-02 at 7 54 38 AM" src="https://github.com/user-attachments/assets/d189951a-b1ff-4123-a0fb-758fa5755ec9">
But the validation is apparently happening on a null string:

<img width="1423" alt="Screenshot 2024-09-02 at 7 56 11 AM" src="https://github.com/user-attachments/assets/fa970769-25b0-4584-a05e-0f1ddb7e1d95">

**Comment by rbyh** [comment]
I am getting this for multiple choice questions as well:

<img width="806" alt="image" src="https://github.com/user-attachments/assets/2938faca-b954-4bed-91ef-bc4e7e6efd84">

**Comment by rbyh** [comment]
Code to reproduce:
```
from edsl import QuestionMultipleChoice, Scenario

q = QuestionMultipleChoice( 
    question_name = """read""", 
    question_text = """Have you read any books about {{ topic }}?""", 
    question_options = ['Yes', 'No', 'I do not know']
)
scenario = Scenario({'topic': 'climate change'})
results = q.by(scenario).run()
```

**Comment by johnjosephhorton** [comment]
I think I've got the fix for this - newline issue. BTW - TIL that if you start "ipython" (instead of python) and you type "%paste" you can run whatever you've copied. This is nicer than having to put in a file
```
In [2]: from edsl import QuestionMultipleChoice, Scenario

In [3]: 

In [3]: q = QuestionMultipleChoice(
   ...:     question_name = """read""",
   ...:         question_text = """Have you read any books about {{ topic }}?""",
   ...:             question_options = ['Yes', 'No', 'I do not know']
   ...:             )

In [4]: scenario = Scenario({'topic': 'climate change'})

In [5]: results = q.by(scenario).run()

In [6]: results.select('answer.*').print()
┏━━━━━━━━┓
┃ answer ┃
┃ .read  ┃
┡━━━━━━━━┩
│ Yes    │
└────────┘

```
