### ISSUE TITLE
Gemini Pro returning response that is not showing up in history report and throwing exception 'LanguageModelBadResponseError'

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#973]
Example showing the issue occurring (only) after agents added to a survey: 
https://www.expectedparrot.com/content/c121cab3-bad1-4b63-9201-a2db638ec932

<img width="755" alt="image" src="https://github.com/user-attachments/assets/2d07f1fc-b8f6-48ac-bd5d-659827ab38d7">

```
raise LanguageModelBadResponseError(message=msg, response_json=data)
edsl.exceptions.language_models.LanguageModelBadResponseError: {'code': 429, 'message': 'Resource has been exhausted (e.g. check quota).', 'status': 'RESOURCE_EXHAUSTED'}
```

**Comment by johnjosephhorton** [comment]
Is this still an issue?

**Comment by rbyh** [comment]
Yes - still happening: https://www.expectedparrot.com/content/a15486da-a49c-4a90-8922-b4cfc8c406ea
