### ISSUE TITLE
include_comment = False generating error with no exceptions report

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#976]
https://www.expectedparrot.com/content/00318f08-e061-45c4-9f93-fd8ad213d13d

Reproduce:
```
from edsl import QuestionMultipleChoice

q = QuestionMultipleChoice(
    question_name = "no_comment",
    question_text = "What's your favorite sport?",
    question_options = ["Sailing", "Swimming", "Tennis"],
    include_comment = False
)
results = q.run()
```

**Comment by rbyh** [comment]
<img width="1233" alt="image" src="https://github.com/user-attachments/assets/2a6bcd3e-39a5-4023-bc88-063823f13536">

**Comment by johnjosephhorton** [comment]
It's because we store comments in a dictionary with a key "{quetion_name}_comment" and later check if something is a comment by this - the name "_comment" screws this up.  As a fix, I'm checking the question name at create and requiring it not end w/ comment or generated tokens and throwing an exception there.

**Comment by rbyh** [comment]
Ah ha, what a great I inadvertently wrote here!

**Comment by nuozhou715** [comment]
Hello,

I tried to include `include_comment=False` in my `QuestionCheckBox`. It returns the following last-line error: 
```python
TypeError: QuestionCheckBox.__init__() got an unexpected keyword argument 'include_comment'
``` 

Not sure if this is an issue related to this discussion? Thanks!

**Comment by johnjosephhorton** [comment]
Thanks! So this is a new feature (shutting off comments) that we are hoping to release (very) soon!

**Comment by nuozhou715** [comment]
I see, thanks for the clarification! That would be super helpful, especially for people with low-tier API rate limits

**Comment by rbyh** [comment]
@nuozhou715  Apologies for the confusion! This features is on main at GitHub but not the latest version at PyPI. Looking forward to hearing what you think!
