### ISSUE TITLE
Add ability to subset results by question/answer

### ISSUE THREAD

**Issue by rbyh** [expectedparrot/edsl#983]
Say I have a very large set of results that I want to break up by question/answer, eg in order to (ultimately) create smaller CSV files that include all the common fields (agents, scenarios, models) but only the question and answer fields for questions that I have specified. Right now there is no straightforward way to do this.

We could create a method that lets you specify the names of the question(s) that you want to include or drop in a subset of results:

```
new_results = results.subset(keep_questions = ["<question_name>", "<question_name>"])
```
or
```
new_results = results.subset(drop_questions = ["<question_name>", "<question_name>"])
```

**Comment by johnjosephhorton** [comment]
What about creating a ScenarioList first and doing it there? Results have a complex structure and separating them would be a annoying & likely break things.

**Comment by rbyh** [comment]
Did `results.to_scenario_list()` get deleted? I no longer see it.

**Comment by rbyh** [comment]
We used to have it: https://docs.expectedparrot.com/en/latest/scenarios.html#turning-results-into-scenarios

**Comment by rbyh** [comment]
Sorry, it is still available. I had an unrelated Coop error. I'll just note in docs that `to_scenario_list()` can be used for this. Thanks.
